// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHnF7rsBgN6FbvoT0HiPPKC0BbpfkegqE',
    appId: '1:531639269253:web:802c7a50c40f15cefcb6ec',
    messagingSenderId: '531639269253',
    projectId: 'ariukathesis',
    authDomain: 'ariukathesis.firebaseapp.com',
    storageBucket: 'ariukathesis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQaCDnV9riOnn9yRfByHX1uJu20ttjkg',
    appId: '1:531639269253:android:0b48b390445d69e4fcb6ec',
    messagingSenderId: '531639269253',
    projectId: 'ariukathesis',
    storageBucket: 'ariukathesis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAebn9VrrzgYFiHzknGJl8Pw9SJWmoXRZo',
    appId: '1:531639269253:ios:18c9f8db7f7a29bafcb6ec',
    messagingSenderId: '531639269253',
    projectId: 'ariukathesis',
    storageBucket: 'ariukathesis.firebasestorage.app',
    iosBundleId: 'com.example.diplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAebn9VrrzgYFiHzknGJl8Pw9SJWmoXRZo',
    appId: '1:531639269253:ios:18c9f8db7f7a29bafcb6ec',
    messagingSenderId: '531639269253',
    projectId: 'ariukathesis',
    storageBucket: 'ariukathesis.firebasestorage.app',
    iosBundleId: 'com.example.diplom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHnF7rsBgN6FbvoT0HiPPKC0BbpfkegqE',
    appId: '1:531639269253:web:d82cb28bba0f2f5cfcb6ec',
    messagingSenderId: '531639269253',
    projectId: 'ariukathesis',
    authDomain: 'ariukathesis.firebaseapp.com',
    storageBucket: 'ariukathesis.firebasestorage.app',
  );

}